### ISSUE TITLE
Dans CIRCULATION, supprimer l'attribut TRANSITION ?

### ISSUE THREAD

**Issue by Marion-Torterotot** [GT-CNIG-Accessibilite-TEAM/GT-CNIG-Accessibilite#12]
L'attribut TRANSITION signale si le tronçon est en montée, descente, plat ou variable (pour les escalators par exemple).
Or, cette information est déjà collectée par l'attribut PENTE du tronçon de cheminement auquel la circulation est liée. La pente étant orientée, il semble que l'information soit collectée deux fois.
Par ailleurs, pour les escalators et tapis roulants, il existe l'attribut SENS qui collecte aussi cette information (puisque, dans leur cas, ce n'est pas la pente "physique" qui donne la transition du tronçon).

Je propose donc de supprimer cet attribut. J'ai cru comprendre qu'il y avait une question de compatibilité NetEX : peut-on s'en affranchir ?

**Comment by Marion-Torterotot** [comment]
Par ailleurs, les attributs SENS de escalators et tapis roulant ne font pas appel à la même liste ("sens" pour tapis roulant et "transition" pour escalators). Ne pourrait-on pas harmoniser cela ? Après tout, il existe aussi des tapis roulant qui montent et descendent !

**Comment by GT-CNIG-DDU** [comment]
Sur ce deuxième point nous ne sommes pas sur les mêmes notions : 
- `sens` exprime la notion de sens de circulation du TAPIS ROULANT
- `transition` exprime la notion de changement de niveau (pour une CIRCULATION et un ESCALATOR )

**Comment by Marion-Torterotot** [comment]
En effet, mon message n'était pas clair.
Ce que je voulais dire c'est que, de mon point de vue :
- "transition" fait doublon avec "pente" (pour circulation et escalator, mais aussi pourquoi pas pour tapis roulant car un tapis roulant peut être incliné)
- l'attribut "sens" n'a pas la même signification entre escalator (ou il signifie en fait "transition") et tapis roulant (ou il signifie en effet bien le sens de fonctionnement du tapis). Ca me paraît déroutant. Par ailleurs, il peut être intéressant de collecter l'information "sens" (de circulation) aussi pour l'escalator (qui peut fonctionner dans les deux sens).
Bref, beaucoup de fois le mot "sens", mais pas toujours dans le même sens... Vous me suivez ? 😄

**Comment by GT-CNIG-DDU** [comment]
Merci @Marion-Torterotot, pour te répondre :

- `transition` est un attribut NeTEX (c'est à dire attendu par NeTEx), il sera difficile de s'en affranchir.

- nous pouvons effectivement renommer ESCALATOR.`sens` en ESCALATOR.`transition` si nécessaire.
C'est effectivement plus cohérent avec CIRCULATION.`transition`.
Le terme de "sens" avait initialement été choisi car on parle plus communément de "sens" que de "transition" pour un escalator. Mais cela peut changer. A débattre en GT ?
