### ISSUE TITLE
Ajouter la valeur : 21 Quai à l'attribut typetronçon

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [GT-CNIG-Accessibilite-TEAM/GT-CNIG-Accessibilite#4]
Pour optimiser la conversion standard CNIG <=> NeTEx, Wegoto a proposé  à la réunion du 25 août 2022 que la valeur "21 - Quai" soit ajoutée à l'attribut typetroncon de TRONCON_CHEMINEMENT, à l'instar des autres valeurs indiquant l'utilisation d'un équipement d'accès.

**Comment by GT-CNIG-ACCESSIBILITE** [comment]
La valeur "quai" a été aoutée à la liste "Type de tronçon"
